version: "3.1"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    command: npm start
    environment:
      - DB_URL=mongodb://mongodb:27017/games
      - PORT=3001
      - NODE_PATH=./src
    depends_on:
      - mongodb
    ports:
      - 3001:3001
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
